export const nationalFeatured: string[] = [
  "Rio de Janeiro – RJ",
  "São Paulo – SP",
  "Porto de Galinhas – PE",
  "Maceió – AL",
  "Fortaleza – CE",
  "Recife – PE",
  "Porto Seguro – BA",
  "Natal – RN",
  "Gramado – RS",
  "Florianópolis – SC",
  "Foz do Iguaçu – PR",
  "Salvador – BA",
  "João Pessoa – PB",
  "Campos do Jordão – SP",
  "Búzios – RJ",
  "Ubatuba – SP",
  "Caldas Novas – GO",
  "Guarujá – SP",
  "Balneário Camboriú – SC",
  "Bombinhas – SC",
];

export const nationalMore: string[] = [
  "Maragogi – AL",
  "Jericoacoara – CE",
  "Arraial d’Ajuda – BA",
  "Trancoso – BA",
  "Aracaju – SE",
  "Praia do Forte – BA",
  "Imbassaí – BA",
  "Arraial do Cabo – RJ",
  "Cabo Frio – RJ",
  "Paraty – RJ",
  "Angra dos Reis – RJ",
  "Morro de São Paulo – BA",
  "Itacaré – BA",
  "Fernando de Noronha – PE",
  "Pipa – RN",
  "São Miguel dos Milagres – AL",
  "Praia dos Carneiros – PE",
  "Canoa Quebrada – CE",
  "Cumbuco – CE",
  "Ilhabela – SP",
  "Maresias – SP",
  "Santos – SP",
  "Ilha Grande – RJ",
  "Ouro Preto – MG",
  "Belo Horizonte – MG",
  "Brasília – DF",
  "Curitiba – PR",
  "Porto Alegre – RS",
  "Canela – RS",
  "Bento Gonçalves – RS",
  "Blumenau – SC",
  "Penha / Beto Carrero – SC",
  "Itapema – SC",
  "Garopaba – SC",
  "Praia do Rosa – SC",
  "Monte Verde – MG",
  "Capitólio – MG",
  "Poços de Caldas – MG",
  "Tiradentes – MG",
  "Petrópolis – RJ",
  "Teresópolis – RJ",
  "Nova Friburgo – RJ",
  "Rio Quente – GO",
  "Pirenópolis – GO",
  "Chapada dos Veadeiros – GO",
  "Bonito – MS",
  "Pantanal – MS/MT",
  "Chapada dos Guimarães – MT",
  "Jalapão – TO",
  "Lençóis Maranhenses – MA",
  "São Luís – MA",
  "Belém – PA",
  "Alter do Chão – PA",
  "Manaus – AM",
  "Chapada Diamantina – BA",
  "Lençóis – BA",
  "Ilhéus – BA",
  "Boipeba – BA",
  "São Miguel do Gostoso – RN",
  "Barra Grande – PI",
  "Delta do Parnaíba – PI",
  "Flecheiras – CE",
  "Icaraizinho de Amontada – CE",
  "Tamandaré – PE",
  "Vitória – ES",
  "Vila Velha – ES",
  "Guarapari – ES",
  "Domingos Martins – ES",
  "Aparecida – SP",
  "Olímpia – SP",
  "Brotas – SP",
  "Socorro – SP",
  "Holambra – SP",
  "Serra Negra – SP",
  "Águas de Lindóia – SP",
  "São Roque – SP",
  "Campos dos Goytacazes – RJ",
  "Nobres – MT",
  "Goiânia – GO",
  "Palmas – TO",
];

export const internationalFeatured: string[] = [
  "Bali — Indonésia",
  "Londres — Reino Unido",
  "Dubai — Emirados Árabes Unidos",
  "Hanói — Vietnã",
  "Paris — França",
  "Roma — Itália",
  "Marrakech — Marrocos",
  "Bangkok — Tailândia",
  "Creta — Grécia",
  "Nova York — Estados Unidos",
  "Tóquio — Japão",
  "Istambul — Turquia",
  "Barcelona — Espanha",
  "Maldivas",
  "Singapura",
  "Cancún — México",
  "Lisboa — Portugal",
  "Amsterdã — Países Baixos",
  "Seul — Coreia do Sul",
];

export const internationalMore: string[] = [
  "Santorini — Grécia",
  "Phuket — Tailândia",
  "Kyoto — Japão",
  "Madrid — Espanha",
  "Hong Kong",
  "Kuala Lumpur — Malásia",
  "Veneza — Itália",
  "Florença — Itália",
  "Milão — Itália",
  "Praga — República Tcheca",
  "Viena — Áustria",
  "Budapeste — Hungria",
  "Berlim — Alemanha",
  "Dublin — Irlanda",
  "Edimburgo — Escócia",
  "Atenas — Grécia",
  "Mykonos — Grécia",
  "Ilha da Madeira — Portugal",
  "Porto — Portugal",
  "Nice — França",
  "Orlando — Estados Unidos",
  "Miami — Estados Unidos",
  "Los Angeles — Estados Unidos",
  "Las Vegas — Estados Unidos",
  "San Francisco — Estados Unidos",
  "Honolulu / Havaí — Estados Unidos",
  "Punta Cana — República Dominicana",
  "Aruba",
  "Curaçao",
  "Bahamas",
  "Jamaica",
  "Saint Martin / Sint Maarten",
  "Barbados",
  "Maurício",
  "Seychelles",
  "Bora Bora — Polinésia Francesa",
  "Cidade do Cabo — África do Sul",
  "Cairo — Egito",
  "Luxor — Egito",
  "Zanzibar — Tanzânia",
  "Abu Dhabi — Emirados Árabes Unidos",
  "Doha — Catar",
  "Jerusalém — Israel",
  "Petra — Jordânia",
  "Mumbai — Índia",
  "Nova Delhi — Índia",
  "Agra / Taj Mahal — Índia",
  "Jaipur — Índia",
  "Pequim — China",
  "Xangai — China",
  "Macau",
  "Taipei — Taiwan",
  "Osaka — Japão",
  "Chiang Mai — Tailândia",
  "Koh Samui — Tailândia",
  "Cidade de Ho Chi Minh — Vietnã",
  "Siem Reap / Angkor Wat — Camboja",
  "Ilha de Boracay — Filipinas",
  "Palawan — Filipinas",
  "Melbourne — Austrália",
  "Auckland — Nova Zelândia",
  "Queenstown — Nova Zelândia",
  "Vancouver — Canadá",
  "Toronto — Canadá",
  "Montreal — Canadá",
  "Cidade do México — México",
  "Los Cabos — México",
  "Tulum — México",
  "Buenos Aires — Argentina",
  "Bariloche — Argentina",
  "Ushuaia — Argentina",
  "Santiago — Chile",
  "San Pedro de Atacama — Chile",
  "Machu Picchu / Cusco — Peru",
  "Lima — Peru",
  "Cartagena — Colômbia",
  "Bogotá — Colômbia",
  "Galápagos — Equador",
  "Patagônia — Argentina/Chile",
];
